### ISSUE TITLE
server side

### ISSUE THREAD

**Issue by MohamadSH** [onepf/OPFPush#21]
Hello ,
Thank you for implementing such great library for pushing notifications. I was wondering if there is a suitable server side PHP class that works fine with your package. I have not found anything yet . I mean what do you use yourself for server side programming of this.
Thanks alot

**Comment by rsavin** [comment]
Hi. Thank you for using. 
We have small backend for testing. It is written on java using Google Cloud Endpoints. It is dirty and doesn't have reusable parts so we didn't open it.
